### ISSUE TITLE
bottle startproject MyProject  has error

### ISSUE THREAD

**Issue by idevsoft** [avelino/bottle-boilerplate#2] opened 2015-05-14 08:11 UTC
Python 2.7.9, run 'bottle startproject MyProject'  has error message :
pkg_resources.VersionConflict: click 4.0 is installed but click<4.0 is required by ['cookiecutter']

Requirement should be updated.

**Comment by erichideki** [comment] 2015-07-13 19:27
I have the same issue.

**Comment by erichideki** [comment] 2015-07-23 13:28
I found the error. My mistake. 

The problem is not the bottle-boilerplate, is the Cookiecutter that not update the version stable of the Click package. I will open an issue of that in Cookiecutter repository.

Until now, the bottle-boilerplate need to be use click==3.3

**Comment by avelino** [comment] 2015-07-23 14:33
Fixed in PR #4 by @erichideki

**Closed as completed by avelino** 2015-07-23 14:33 UTC
Labels: bug
